#!/usr/bin/env bash
# Scaffold a sandbox replay workspace for a finding.
#
# Creates the directory structure and skeleton docker-compose.yml for the
# sandbox-replay agent. The agent does the smart work (technology mapping,
# PoC generation, evidence capture); this script handles scaffolding and
# teardown.
#
# Usage:
#   bash automation/sandbox_setup.sh --target <name> --finding <id>
#   bash automation/sandbox_setup.sh --target <name> --finding <id> --teardown
#
# Requires: Docker (checked at startup)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# --- Defaults ---
TARGET=""
FINDING=""
TEARDOWN=false

# --- Usage ---
usage() {
  cat <<'USAGE'
Usage:
  bash automation/sandbox_setup.sh --target <name> --finding <id>
  bash automation/sandbox_setup.sh --target <name> --finding <id> --teardown

Options:
  --target <name>    Target slug (e.g., ExampleCorp)
  --finding <id>     Finding ID (e.g., EX-001)
  --teardown         Stop and remove sandbox containers (preserves evidence)
  -h, --help         Show this help

Examples:
  bash automation/sandbox_setup.sh --target ExampleCorp --finding EX-001
  bash automation/sandbox_setup.sh --target ExampleCorp --finding EX-001 --teardown
USAGE
  exit 1
}

# --- Parse args ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)   TARGET="$2"; shift 2 ;;
    --finding)  FINDING="$2"; shift 2 ;;
    --teardown) TEARDOWN=true; shift ;;
    -h|--help)  usage ;;
    *)          echo "[!] Unknown option: $1" >&2; usage ;;
  esac
done

if [[ -z "$TARGET" || -z "$FINDING" ]]; then
  echo "[!] --target and --finding are required." >&2
  usage
fi

# --- Resolve workspace root ---
if [[ -f "$ROOT/.workspace_root" ]]; then
  WORKSPACE_ROOT=$(cat "$ROOT/.workspace_root")
  WORKSPACE_ROOT="${WORKSPACE_ROOT%/}"
  [[ "$WORKSPACE_ROOT" != /* ]] && WORKSPACE_ROOT="$ROOT/$WORKSPACE_ROOT"
elif [[ -d "$ROOT/workspace" ]]; then
  WORKSPACE_ROOT="$ROOT/workspace"
else
  echo "[!] No workspace found. Run: bash automation/setup_workspace.sh" >&2
  exit 1
fi

SANDBOX_DIR="$WORKSPACE_ROOT/workshop/$TARGET/sandbox/$FINDING"

# --- Teardown mode ---
if $TEARDOWN; then
  if [[ ! -f "$SANDBOX_DIR/docker-compose.yml" ]]; then
    echo "[!] No sandbox found at $SANDBOX_DIR" >&2
    exit 1
  fi
  echo "[*] Tearing down sandbox for $TARGET / $FINDING..."
  docker compose -f "$SANDBOX_DIR/docker-compose.yml" down --volumes --remove-orphans 2>/dev/null || true
  echo "[+] Containers removed. Evidence preserved in $SANDBOX_DIR/evidence/"
  exit 0
fi

# --- Pre-flight: Docker check ---
if ! docker info >/dev/null 2>&1; then
  echo "[!] Docker is not available. Start Docker Desktop or dockerd first." >&2
  exit 1
fi

# --- Create directory structure ---
if [[ -d "$SANDBOX_DIR" ]]; then
  echo "[*] Sandbox directory already exists: $SANDBOX_DIR"
  echo "    Use --teardown to clean up, or remove manually."
else
  echo "[*] Creating sandbox workspace: $SANDBOX_DIR"
  mkdir -p "$SANDBOX_DIR"/{app,db-init,evidence}
fi

# --- Generate skeleton docker-compose.yml ---
COMPOSE_FILE="$SANDBOX_DIR/docker-compose.yml"
if [[ -f "$COMPOSE_FILE" ]]; then
  echo "[skip] docker-compose.yml already exists."
else
  cat > "$COMPOSE_FILE" <<YAML
# Sandbox for ${TARGET} / ${FINDING}
# Generated by sandbox_setup.sh — customize before use.
# The sandbox-replay agent will replace this with a tailored configuration.

version: "3.8"

services:
  app:
    image: ubuntu:22.04
    container_name: sandbox-${TARGET,,}-${FINDING,,}
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./evidence:/evidence
    networks:
      - sandbox-net
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    command: ["echo", "Replace this with the actual application setup"]

networks:
  sandbox-net:
    driver: bridge
    internal: true
YAML
  echo "[+] Skeleton docker-compose.yml created."
fi

# --- Generate setup.sh ---
SETUP_FILE="$SANDBOX_DIR/setup.sh"
if [[ ! -f "$SETUP_FILE" ]]; then
  cat > "$SETUP_FILE" <<'SETUP'
#!/usr/bin/env bash
set -euo pipefail
SANDBOX_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TIMESTAMP=$(date '+%Y%m%d_%H%M%S')
EVIDENCE_DIR="${SANDBOX_DIR}/evidence/${TIMESTAMP}"
mkdir -p "$EVIDENCE_DIR"

if ! docker info >/dev/null 2>&1; then
  echo "[!] Docker is not running." >&2; exit 1
fi

docker compose -f "${SANDBOX_DIR}/docker-compose.yml" pull
docker compose -f "${SANDBOX_DIR}/docker-compose.yml" up -d
echo "[+] Sandbox started. Evidence dir: ${EVIDENCE_DIR}"
echo "[*] To stop: bash teardown.sh"
SETUP
  chmod +x "$SETUP_FILE"
  echo "[+] setup.sh created."
fi

# --- Generate teardown.sh ---
TEARDOWN_FILE="$SANDBOX_DIR/teardown.sh"
if [[ ! -f "$TEARDOWN_FILE" ]]; then
  cat > "$TEARDOWN_FILE" <<'TEARDOWN'
#!/usr/bin/env bash
set -euo pipefail
SANDBOX_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
docker compose -f "${SANDBOX_DIR}/docker-compose.yml" down --volumes --remove-orphans
echo "[+] Sandbox stopped. Evidence preserved in evidence/"
TEARDOWN
  chmod +x "$TEARDOWN_FILE"
  echo "[+] teardown.sh created."
fi

echo ""
echo "=== Sandbox scaffolding complete ==="
echo "  Directory: $SANDBOX_DIR"
echo "  Next: run the sandbox-replay agent to generate a tailored docker-compose.yml"
echo "  Or:   edit docker-compose.yml manually, then: bash $SANDBOX_DIR/setup.sh"
